apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: jambonz-monitoring
spec:
  ports:
    - name: "influxdb"
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  clusterIP: None
