apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server
  namespace: jambonz
spec:
  rules:
    - host: api.k8s-gcp.jambonz.org
      http:
        paths:
        - backend:
            service:
              name: api-server
              port: 
                number: 3000
          path: /
          pathType: Prefix

