apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-binding
  namespace: jambonz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-jobs
subjects:
  - kind: ServiceAccount
    name: default
