steps:
- name: 'gcr.io/drachtio-cpaas/packer'
  args:
  - build
  - -var
  - image_name=jambonz-mini-082
  - -var
  - project_id=drachtio-cpaas
  - -var
  - image_family=debian-11-bullseye-v20230306
  - -var
  - image_zone=us-central1-c
  - template.json
