apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-jobs
  namespace: jambonz
rules:
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - cronjobs/status
      - jobs
      - jobs/status
    verbs:
      - get
      - list
      - watch