apiVersion: v1
kind: Secret
metadata:
    name: jambonz-secrets
    namespace: jambonz
type: Opaque
data:
    # use 32 bytes of random value, hex
    MYSQL_PASSWORD: amFtYm9uZXM=
    DRACHTIO_SECRET: Y3ltcnU=
    JWT_SECRET: Rz11JS05NyNUZmZZZg==