apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbc-outbound
  labels:
    app: sbc-outbound
  namespace: jambonz
spec:
  selector:
    matchLabels:
      app: sbc-outbound
  template:
    metadata:
      labels:
        app: sbc-outbound
    spec:
      initContainers:
        - args:
            - wait
            - --for=condition=complete
            - --timeout=300s
            - job/db-create
          image: d3fk/kubectl:v1.18
          name: db-create-wait
      containers:
        - name: sbc-outbound
          image: jambonz/sbc-outbound:k8s
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: jambonz-env
          env:
            - name: DRACHTIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: DRACHTIO_SECRET
            - name: DRACHTIO_PORT
              value: "3000"
