apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtpengine-ng
  name: rtpengine-ng
  namespace: jambonz
spec:
  ports:
    - name: ng
      port: 22222
      protocol: UDP
      targetPort: 22222
  selector:
    app: jambonz-sbc-rtp
  clusterIP: None
