apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: jambonz
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: jambonz-env
                  key: JAMBONES_MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: jambonz-env
                  key: JAMBONES_MYSQL_USER
          image: mysql
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - 127.0.0.1
                - --protocol
                - tcp
            failureThreshold: 10
            timeoutSeconds: 5
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-claim
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: mysql-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
