apiVersion: v1
kind: Service
metadata:
  labels:
    app: telegraf
  name: telegraf
  namespace: jambonz-monitoring
spec:
  ports:
    - name: telegraf
      port: 8125
      targetPort: 8125
  selector:
    app: telegraf
  clusterIP: None
