apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: jambonz
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  clusterIP: None
